apiVersion: 1
datasources:
  - name: Prometheus
    uid: prom
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData: { timeInterval: 30s }
  - name: Loki
    uid: loki
    type: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - { name: trace, matcherType: label, matcherRegex: trace_id, datasourceUid: tempo, url: '$${__value.raw}' }
  - name: Tempo
    uid: tempo
    type: tempo
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2: { datasourceUid: loki, filterByTraceID: true, spanStartTimeShift: -5m, spanEndTimeShift: 5m }
      serviceMap: { datasourceUid: prom }
