#!/usr/bin/env bash
# Writes Cloudflare's edge ranges for nginx: who may connect (geo) and whose CF-Connecting-IP to believe (real_ip).
# Run once at setup and whenever Cloudflare changes its ranges (rarely); then `nginx -t && systemctl reload nginx`.
set -euo pipefail
ips=$(curl -fsS https://www.cloudflare.com/ips-v4; echo; curl -fsS https://www.cloudflare.com/ips-v6)
{ echo "# generated by cloudflare-ips.sh"; for ip in $ips; do echo "set_real_ip_from $ip;"; done; echo "real_ip_header CF-Connecting-IP;"; } > /etc/nginx/cloudflare-realip.conf
{ echo "# generated by cloudflare-ips.sh"; for ip in $ips; do echo "$ip 1;"; done; } > /etc/nginx/cloudflare-geo.conf
echo "wrote $(echo "$ips" | wc -w) ranges"
